#!/bin/bash

#SBATCH -J ELECTRAEXTEND

#SBATCH -A eecs

#SBATCH -p dgx2

#SBATCH --gres=gpu:3

#SBATCH -o ELECTRAGENEXTEND.out

#SBATCH -e ELECTRAGENEXTEND.err

#SBATCH --mail-type=BEGIN,END,FAIL

#SBATCH --mail-user=varmar@oregonstate.edu

source ~/guille/torch10.1/bin/activate

python begin.py -c ~/guille/train_encodings_512.npy -t ~/guille/test_encodings_512.npy -v ~/guille/vocab_embeddings.npy -o ~/models/basegen/basegenextend -b 32 -l 10 -e 60 -a 10 -s 513 --cuda --log_file ~/models/basegen/basegenextend.txt --load_gen ~/models/basegen/test_epoch150_gen/pytorch_model.bin --load_g_embed ~/models/basegen/test_epoch150gen_embed
