#!/bin/bash

#SBATCH -J ELECTRAGEN

#SBATCH -A eecs

#SBATCH -p dgx2

#SBATCH --gres=gpu:2

#SBATCH -o ELECTRAGEN.out

#SBATCH -e ELECTRAGEN.err

#SBATCH --mail-type=BEGIN,END,FAIL

#SBATCH --mail-user=varmar@oregonstate.edu

source ~/guille/torch10.1/bin/activate

python begin.py -c ~/guille/train_encodings_512.npy -t ~/guille/test_encodings_512.npy -v ~/guille/vocab_embeddings.npy -o ~/models/gensgdlr1e2/gen -b 32 -l 10 -e 200 -a 10 -s 513 --cuda --log_file ~/models/gensgdlr1e2/gen.txt \
--resume_epoch 200 --load_gen ~/models/gensgdlr1e2/gen_epoch199_gen/pytorch_model.bin --load_g_embed ~/models/gensgdlr1e2/gen_epoch199_gen_embed
