#!/bin/bash

#SBATCH -J ELECTRAlossweightanalysis

#SBATCH -A eecs

#SBATCH -p dgx2

#SBATCH --gres=gpu:6

#SBATCH -o ELECTRAlossweight.out

#SBATCH -e ELECTRAlossweight.err

#SBATCH --mail-type=BEGIN,END,FAIL

#SBATCH --mail-user=varmar@oregonstate.edu

source ~/guille/torch10.1/bin/activate


#python begin.py -c ~/guille/train_encodings_512.npy -t ~/guille/test_encodings_512.npy -v ~/guille/vocab_embeddings.npy -o ~/models/alborz_lw/pretrain_512_dlw25 -b 10 -l 10 -e 20 -s 513 --cuda --log_file ~/models/alborz_lw/pretrain_512_dlw25.txt --d_loss_weight 25.0 \
#--load_gen ~/models/gen_only/gen_only_100ep_1e2_epoch119_gen/pytorch_model.bin --load_g_embed ~/models/gen_only/gen_only_100ep_1e2_epoch119_gen_embed

#python begin.py -c ~/guille/train_encodings_512.npy -t ~/guille/test_encodings_512.npy -v ~/guille/vocab_embeddings.npy -o ~/models/alborz_lw/pretrain_512_dlw10 -b 10 -l 10 -e 20 -s 513 --cuda --log_file ~/models/alborz_lw/pretrain_512_dlw10.txt --d_loss_weight 10.0 \
#--load_gen ~/models/gen_only/gen_only_100ep_1e2_epoch119_gen/pytorch_model.bin --load_g_embed ~/models/gen_only/gen_only_100ep_1e2_epoch119_gen_embed

python begin.py -c ~/guille/train_encodings_512.npy -t ~/guille/test_encodings_512.npy -v ~/guille/vocab_embeddings.npy -o ~/models/alborz_lw/pretrain_512_glw25 -b 10 -l 10 -e 25 -s 513 --cuda --log_file ~/models/alborz_lw/pretrain_512_glw25.txt --g_loss_weight 25.0 --d_loss_weight 1.0 \
--load_gen ~/models/gen_only/gen_only_100ep_1e2_epoch119_gen/pytorch_model.bin --load_g_embed ~/models/gen_only/gen_only_100ep_1e2_epoch119_gen_embed

python begin.py -c ~/guille/train_encodings_512.npy -t ~/guille/test_encodings_512.npy -v ~/guille/vocab_embeddings.npy -o ~/models/alborz_lw/pretrain_512_glw5 -b 10 -l 10 -e 25 -s 513 --cuda --log_file ~/models/alborz_lw/pretrain_512_glw5.txt --g_loss_weight 5.0 --d_loss_weight 1.0 \
--load_gen ~/models/gen_only/gen_only_100ep_1e2_epoch119_gen/pytorch_model.bin --load_g_embed ~/models/gen_only/gen_only_100ep_1e2_epoch119_gen_embed

python begin.py -c ~/guille/train_encodings_512.npy -t ~/guille/test_encodings_512.npy -v ~/guille/vocab_embeddings.npy -o ~/models/alborz_lw/pretrain_512_glw10 -b 10 -l 10 -e 25 -s 513 --cuda --log_file ~/models/alborz_lw/pretrain_512_glw10.txt --g_loss_weight 10.0 --d_loss_weight 1.0 \
--load_gen ~/models/gen_only/gen_only_100ep_1e2_epoch119_gen/pytorch_model.bin --load_g_embed ~/models/gen_only/gen_only_100ep_1e2_epoch119_gen_embed

python begin.py -c ~/guille/train_encodings_512.npy -t ~/guille/test_encodings_512.npy -v ~/guille/vocab_embeddings.npy -o ~/models/alborz_lw/pretrain_512_dlw5 -b 10 -l 10 -e 25 -s 513 --cuda --log_file ~/models/alborz_lw/pretrain_512_dlw5.txt --d_loss_weight 5.0 \
--load_gen ~/models/gen_only/gen_only_100ep_1e2_epoch119_gen/pytorch_model.bin --load_g_embed ~/models/gen_only/gen_only_100ep_1e2_epoch119_gen_embed

python begin.py -c ~/guille/train_encodings_512.npy -t ~/guille/test_encodings_512.npy -v ~/guille/vocab_embeddings.npy -o ~/models/alborz_lw/pretrain_512_lw1 -b 10 -l 10 -e 25 -s 513 --cuda --log_file ~/models/alborz_lw/pretrain_512_lw1.txt --d_loss_weight 1.0 \
--load_gen ~/models/gen_only/gen_only_100ep_1e2_epoch119_gen/pytorch_model.bin --load_g_embed ~/models/gen_only/gen_only_100ep_1e2_epoch119_gen_embed





