#!/bin/bash

#SBATCH -J ELECTRAlim100id

#SBATCH -A eecs

#SBATCH -p dgx2

#SBATCH --gres=gpu:8

#SBATCH -o ELECTRALIM100id.out

#SBATCH -e ELECTRALIM100id.err

#SBATCH --mail-type=BEGIN,END,FAIL

#SBATCH --mail-user=varmar@oregonstate.edu

source ~/guille/torch10.1/bin/activate
python begin.py -c ~/guille/train_encodings_2d.npy -t ~/guille/test_encodings_2d.npy -v ~/guille/vocab_embeddings.npy -o ~/guille/model_store/freqlimit100electra/freqlimit100electraembed/freqlimit100electraembed -b 36 -l 10 -e 20 --cuda --log_file ~/guille/model_store/freqlimit100electra/freqlimit100electraembed/freq_limit_100_electra_embed_log.txt --input_embed