#!/bin/bash

#SBATCH -J ELECTRAlim100id

#SBATCH -A eecs

#SBATCH -p dgx2

#SBATCH --gres=gpu:8

#SBATCH -o ELECTRALIM100id.out

#SBATCH -e ELECTRALIM100id.err

#SBATCH --mail-type=BEGIN,END,FAIL

#SBATCH --mail-user=varmar@oregonstate.edu

#source ~/guille/torch10.1/bin/activate

python begin.py -c ~/guille/IBD_train_512.npy -t ~/guille/IBD_test_512.npy -tl ~/guille/IBD_train_label.npy -tel ~/guille/IBD_test_label.npy -v ~/guille/vocab_embeddings.npy -o ~/models/discsgdlr1e2/nodiscibd/ibd1l10h -b 32 -l 1 -e 20 -a 10 --cuda --log_file ~/models/discsgdlr1e2/nodiscibd/ibd1l10h.txt --num_labels=2 -s 513 --freeze