#!/bin/bash

#SBATCH -J ELECTRAlim100id

#SBATCH -A eecs

#SBATCH -p dgx2

#SBATCH --gres=gpu:8

#SBATCH -o ELECTRALIM100id.out

#SBATCH -e ELECTRALIM100id.err

#SBATCH --mail-type=BEGIN,END,FAIL

#SBATCH --mail-user=varmar@oregonstate.edu

#source ~/guille/torch10.1/bin/activate

python begin.py -c ~/guille/IBD_train_512.npy -t ~/guille/IBD_test_512.npy -tl ~/guille/IBD_train_label.npy -tel ~/guille/IBD_test_label.npy -v ~/guille/vocab_embeddings.npy -o ~/guille/models/ibdelectra512 -b 48 -l 10 -e 20 --cuda --log_file ~/guille/models/ibdelectra512.txt --num_labels=2 --load_disc ~/guille/models/pretrain_512_epoch4_disc/pytorch_model.bin --load_embed ~/guille/models/pretrain_512_epoch4_embed -s 513



